version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dani54196
      POSTGRES_PASSWORD: example
      POSTGRES_DB: gorm
    ports:
      - 5432:5432
    volumes:
      - ./vol:/var/lib/postgresql/data
